version: '2.3'
services:

  api-1:
    #hostname: 10.10.0.10
    build: cinema-http/
    mem_limit: 512M
    ports:
      - "9010:9000"
    cpus: 0.4
    volumes:
     - ./etc/hosts:/etc/hosts
    networks:
      cinema:
        ipv4_address: 10.10.0.101

  api-2:
    #hostname: 10.10.0.10
    build: cinema-http/
    mem_limit: 512M
    ports:
      - "9020:9000"
    cpus: 0.4
    volumes:
     - ./etc/hosts:/etc/hosts
    networks:
      cinema:
        ipv4_address: 10.10.0.102

  api-3:
    #hostname: 10.10.0.10
    build: cinema-http/
    mem_limit: 512M
    ports:
      - "9030:9000"
    cpus: 0.4
    volumes:
     - ./etc/hosts:/etc/hosts
    networks:
      cinema:
        ipv4_address: 10.10.0.103

  cinema-lb:
    image: haproxy:alpine
    mem_limit: 256M
    cpus: 0.25
    ports:
      - "9000:9000"
    volumes:
     - ./etc/hosts:/etc/hosts
     - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
     - api-1
     - api-2
     - api-3
    networks:
      cinema:
        ipv4_address: 10.10.0.100

#  mysql:
#    image: mysql:5.7
#    mem_limit: 512M
#    cpus: 0.25
#    ports:
#      - "3306:3306"
#    volumes:
#         - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
#         - ./sql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
#    restart: always
#    networks:
#      cinema:
#        ipv4_address: 10.10.0.110
#    environment:
#      MYSQL_ROOT_PASSWORD: cinemapass
#      MYSQL_USER: cinema
#      MYSQL_PASSWORD: cinemapass
#      MYSQL_DATABASE: cinema_db

  postgres:
    image: postgres
    mem_limit: 128M
    cpus: 0.25
    ports:
      - "5555:5432"
    volumes:
         - ./sql/initpg.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      cinema:
        ipv4_address: 10.10.0.130
    environment:
      MYSQL_ROOT_PASSWORD: cinemapass
      POSTGRES_USER: cinema
      POSTGRES_PASSWORD: cinemapass
      POSTGRES_DB: cinema_db

#  cinema-www:
#    build: frontend/
#    mem_limit: 256M
#    volumes:
#     - ./etc/hosts:/etc/hosts
#    ports:
#      - "80:80"
#    cpus: 0.25
#    networks:
#      cinema:
#        ipv4_address: 10.10.0.200

  cinema-gateway:
    build: cinema-gateway/
    mem_limit: 256M
    ports:
      - "8000:8000"
    cpus: 0.25
    volumes:
      - ./etc/hosts:/etc/hosts
    networks:
      cinema:
        ipv4_address: 10.10.0.10
        
  graphite:
    image: graphiteapp/graphite-statsd
    volumes:
      - ./graphite/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
    ports:
      - "7080:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125"
      - "8126:8126"
    networks:
      cinema:
        ipv4_address: 10.10.0.222
        
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      cinema:
        ipv4_address: 10.10.0.233  

  jenkins:
    image: jenkins/jenkins:lts
    user: jenkins
    volumes:
      - ./jenkins/secrets:/var/jenkins_home/secrets
    ports:
      - "8080:8080"
      - "5000:5000"
      - "50000:50000"
    environment:
      JENKINS_HOST_HOME: "data/jenkins"  

networks:
  cinema:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.0.0/16
    driver_opts:
       com.docker.network.bridge.default_bridge: "false"
       com.docker.network.bridge.enable_icc: "true"
       com.docker.network.bridge.enable_ip_masquerade: "true"
       com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
       com.docker.network.bridge.name: "docker1"
       com.docker.network.driver.mtu: "1500"
